version: 3.4

services:
  web-1:
    build:
      context: .
      dockerfile: web.container
      args:
        NGINX_VERSION:
    container_name: web-1
    restart: unless-stopped
    networks: 
      - default
    ports:
      - "8081:80"
  
  web-2:
    image: web-server:v1
    container-name: web-2
    restart: unless-stopped
    networks:
      - default
    ports:
      - 8082:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

networks:
  default:
    bridge: